CREATE TABLE IF NOT EXISTS connect_metadata (
  arn VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  arn_type VARCHAR (64) NOT NULL ,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(arn)
);
