CREATE TABLE IF NOT EXISTS historical_metric_data (
  queue_arn VARCHAR(255) NOT NULL, 
  queue_name VARCHAR(255) NOT NULL, 
  start_time BIGINT NOT NULL, 
  end_time BIGINT NOT NULL, 
  abandon_time INT DEFAULT NULL, 
  after_contact_work_time INT, 
  api_contacts_handled INT, 
  callback_contacts_handled INT, 
  contacts_abandoned INT, 
  contacts_agent_hung_up_first INT, 
  contacts_consulted INT, 
  contacts_handled INT, 
  contacts_handled_incoming INT, 
  contacts_handled_outbound INT, 
  contacts_hold_abandons INT, 
  contacts_missed INT, 
  contacts_queued INT,
  contacts_transferred_in INT,
  contacts_transferred_in_from_queue INT,
  contacts_transferred_out INT,
  contacts_transferred_out_from_queue INT,
  handle_time INT,
  hold_time INT,
  interaction_and_hold_time INT,
  interaction_time INT,
  occupancy FLOAT,
  queue_answer_time INT,
  queued_time INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (queue_arn, start_time, end_time)
);